name: Release

on:
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    env: 
      working-directory: ./crowdbotics-slack-app

    steps:
      - name: Initialize packages
        run: |
          sudo apt update
          sudo apt install jo git -y

      - name: Checkout 
        run: |
          git clone https://github.com/crowdbotics/crowdbotics-slack-app.git 

      - name: Generate Json data
        working-directory: ${{ env.working-directory }}
        run: |
          jo -p -- -s tag_name="$(date '+%Y%m%d'.1)" name="Production Release" body="$(git log --oneline --no-decorate HEAD...$(git tag -l '202[0-9]????.*' --sort=-v:refname | head -n 1))" > data.json
          jo last_tag=$(git describe --tags --abbrev=0)
      
      - name: Perform Release
        working-directory: ${{ env.working-directory }}
        run: |
          cat data.json
          curl  -i -X POST -H "Content-Type:application/json" -H "Authorization:token ${{ secrets.TOKEN }}" "https://api.github.com/repos/$GITHUB_REPOSITORY/releases" -d @data.json

  
